apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy first
  labels:
    app: redis-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cache
  template:
    metadata:
      name: redis-cache
      labels:
        app: redis-cache
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          command: ["redis-server"]
          args:
          - --maxmemory 256mb
          - --maxmemory-policy allkeys-lru
          - --save ""  # Disable persistence for better performance
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 5
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: redis-cache
  ports:
    - port: 6379
      targetPort: 6379
      