apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiment-model-config
data:
  model_config.json: |
    {
      "model_name": "cardiffnlp/twitter-roberta-base-sentiment-latest",
      "max_length": 512,
      "batch_size": 8,
      "confidence_threshold": 0.8
    }
  app_config.yaml: |
    logging:
      level: INFO
    api:
      timeout: 30
      rate_limit: 100
