apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-model
spec:
  template:
    spec:
      containers:
      - name: sentiment-model
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: MODEL_CACHE_SIZE
          value: "100"
        # M3 Mac development optimizations
        - name: PYTORCH_ENABLE_MPS_FALLBACK
          value: "1"
        - name: OMP_NUM_THREADS
          value: "4"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"