#file: noinspection KubernetesUnknownValues
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development
# 👈 Get the base resources from here
resources:
  - ../../base
# 👈 Add environment-specific labels
labels:
  - includeSelectors: true
    pairs:
      environment: development
      deployment-type: auto
      monitoring: enabled
# 👈 Apply this patch file to modify resources
patches:
  - target:
      kind: Deployment
      name: sentiment-model
    path: development-patch.yaml
# 👈 Override replica count
replicas:
  - count: 5
    name: sentiment-model
# 👈 Create new config maps
configMapGenerator:
  - name: dev-config
    literals:
      - LOG_LEVEL=DEBUG
      - CACHE_TTL=50
      - MAX_REQUESTS_PER_MINUTE=1000

