apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

labels:
  - includeSelectors: true
    pairs:
      app: sentiment-model
      team: ai-platform
      managed-by: kustomize
